# Generated by Django 2.2.1 on 2019-05-08 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190508_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('node', models.IntegerField()),
                ('autor', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('sellnum', models.IntegerField()),
                ('discription', models.TextField()),
                ('imagesource', models.TextField(default='http://image.yes24.com/momo/TopCate1833/MidCate006/183255693.jpg', validators=[django.core.validators.URLValidator])),
            ],
        ),
    ]
