# Generated by Django 2.2.1 on 2019-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190508_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
    ]
