# Generated by Django 2.2.1 on 2019-05-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190509_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discription',
            new_name='description',
        ),
    ]
