# Generated by Django 2.2.1 on 2019-05-09 12:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190509_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=20),
        ),
    ]
